from __future__ import annotations

import argparse
import json
import uuid
from pathlib import Path


KIT_ROOT = Path(__file__).resolve().parents[1]
SOURCE_SCRIPTS = KIT_ROOT / "ops-seed"
TEMPLATES = KIT_ROOT / "templates"

OPS_SCRIPTS = [
    "resolve_delivery_channel.sh",
    "safe_message_send.sh",
    "whatsapp_target_resolver.sh",
    "whatsapp_task_governance.sh",
    "whatsapp_send_with_retry.sh",
    "whatsapp_restart_preserve_queue.sh",
    "whatsapp_staged_queue_drain.sh",
    "whatsapp_delivery_guard.sh",
    "whatsapp_delivery_audit.sh",
    "whatsapp_problem_notifier.sh",
    "whatsapp_directory_sync.sh",
    "whatsapp_contingency_check.sh",
    "whatsapp_group_probe.sh",
]


def render_text(template_name: str, replacements: dict[str, str]) -> str:
    text = (TEMPLATES / template_name).read_text(encoding="utf-8")
    for key, value in replacements.items():
        text = text.replace(f"__{key}__", value)
    return text


def bootstrap_block(container_name: str, account_id: str) -> str:
    return "\n".join(
        [
            "# Generated by setup-kit/render_setup.py",
            'SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
            'OPENCLAW_ROOT="${OPENCLAW_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"',
            'STATE_ROOT="${STATE_ROOT:-$OPENCLAW_ROOT/config}"',
            f'CONTAINER="${{CONTAINER:-{container_name}}}"',
            f'ACCOUNT_ID="${{ACCOUNT_ID:-{account_id}}}"',
            'CHANNEL_RESOLVER="${CHANNEL_RESOLVER:-$OPENCLAW_ROOT/tools/ops/resolve_delivery_channel.sh}"',
            'WHATSAPP_SENDER="${WHATSAPP_SENDER:-$OPENCLAW_ROOT/tools/ops/whatsapp_send_with_retry.sh}"',
            'RESOLVER="${RESOLVER:-$OPENCLAW_ROOT/tools/ops/whatsapp_target_resolver.sh}"',
            'WATCHDOG="${WATCHDOG:-$OPENCLAW_ROOT/tools/ops/whatsapp_delivery_guard.sh}"',
            'GOVERNANCE="${GOVERNANCE:-$OPENCLAW_ROOT/tools/ops/whatsapp_task_governance.sh}"',
            'SENDER="${SENDER:-$OPENCLAW_ROOT/tools/ops/safe_message_send.sh}"',
            'NOTIFIER="${NOTIFIER:-$OPENCLAW_ROOT/tools/ops/whatsapp_problem_notifier.sh}"',
            'SAFE_RESTART="${SAFE_RESTART:-$OPENCLAW_ROOT/tools/ops/whatsapp_restart_preserve_queue.sh}"',
            "",
        ]
    )


def render_ops(output_root: Path, container_name: str, account_id: str) -> None:
    ops_root = output_root / "tools" / "ops"
    ops_root.mkdir(parents=True, exist_ok=True)
    prefix = bootstrap_block(container_name, account_id)
    for script_name in OPS_SCRIPTS:
        source = SOURCE_SCRIPTS / script_name
        target = ops_root / script_name
        text = source.read_text(encoding="utf-8").lstrip("\ufeff")
        if text.startswith("#!/"):
            first, rest = text.split("\n", 1)
            rendered = first + "\n" + prefix + rest
        else:
            rendered = prefix + text
        target.write_text(rendered, encoding="utf-8")
    install_script = output_root / "tools" / "install_whatsapp_ops.sh"
    install_script.write_text(
        "\n".join(
            [
                "#!/usr/bin/env bash",
                "set -euo pipefail",
                'ROOT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"',
                'TOOLS_DIR="$ROOT/tools/ops"',
                'CRON_FILE="/etc/cron.d/openclaw-whatsapp-ops"',
                'mkdir -p "$TOOLS_DIR"',
                'chmod +x "$TOOLS_DIR"/*.sh "$ROOT/tools/install_whatsapp_ops.sh" 2>/dev/null || true',
                'cat > "$CRON_FILE" <<EOF',
                "SHELL=/bin/bash",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "",
                '*/2 * * * * root OPENCLAW_ROOT=$ROOT "$TOOLS_DIR/whatsapp_delivery_audit.sh" >/dev/null 2>&1',
                '*/2 * * * * root OPENCLAW_ROOT=$ROOT "$TOOLS_DIR/whatsapp_delivery_guard.sh" >/dev/null 2>&1',
                '*/2 * * * * root OPENCLAW_ROOT=$ROOT "$TOOLS_DIR/whatsapp_staged_queue_drain.sh" >/dev/null 2>&1',
                '*/5 * * * * root OPENCLAW_ROOT=$ROOT "$TOOLS_DIR/whatsapp_directory_sync.sh" >/dev/null 2>&1',
                '*/5 * * * * root OPENCLAW_ROOT=$ROOT "$TOOLS_DIR/whatsapp_contingency_check.sh" >/dev/null 2>&1',
                "EOF",
                'chmod 644 "$CRON_FILE"',
                "systemctl reload cron >/dev/null 2>&1 || systemctl reload crond >/dev/null 2>&1 || true",
                "",
            ]
        ),
        encoding="utf-8",
    )


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Render a sanitized OpenClaw setup package.")
    parser.add_argument("--output", required=True)
    parser.add_argument("--client-slug", required=True)
    parser.add_argument("--display-name", required=True)
    parser.add_argument("--container-name", required=True)
    parser.add_argument("--account-id", required=True)
    parser.add_argument("--gateway-token", required=True)
    parser.add_argument("--allowed-origin", required=True)
    parser.add_argument("--gateway-port", default="18789")
    parser.add_argument("--webchat-port", default="18790")
    args = parser.parse_args()

    output_root = Path(args.output).resolve()
    output_root.mkdir(parents=True, exist_ok=True)

    replacements = {
        "CLIENT_SLUG": args.client_slug,
        "DISPLAY_NAME": args.display_name,
        "CONTAINER_NAME": args.container_name,
        "ACCOUNT_ID": args.account_id,
        "GATEWAY_TOKEN": args.gateway_token,
        "ALLOWED_ORIGIN": args.allowed_origin,
        "GATEWAY_PORT": str(args.gateway_port),
        "WEBCHAT_PORT": str(args.webchat_port),
        "ENV_OPENAI_API_KEY": "${OPENAI_API_KEY}",
        "ENV_OPENROUTER_API_KEY": "${OPENROUTER_API_KEY}",
        "ENV_GEMINI_API_KEY": "${GEMINI_API_KEY}",
        "JOB_ID_DAILY_MEMORY": str(uuid.uuid4()),
        "JOB_ID_QUEUE_WATCH": str(uuid.uuid4()),
    }

    write_text(output_root / "config" / "openclaw.json", render_text("openclaw.template.json", replacements))
    write_text(output_root / "config" / "cron" / "jobs.json", render_text("cron.jobs.template.json", replacements))
    write_text(output_root / "config" / "agents" / "hq" / "agent" / "instructions.md", render_text("agent.base.instructions.md", replacements))
    write_text(output_root / "config" / "agents" / "orquestrador" / "agent" / "instructions.md", render_text("agent.orquestrador.instructions.md", replacements))
    write_text(output_root / "config" / "MEMORY.md", render_text("MEMORY_TEMPLATE.md", replacements))
    write_text(output_root / "config" / "SOUL.md", render_text("SOUL_TEMPLATE.md", replacements))
    write_text(output_root / "docker-compose.yml", render_text("docker-compose.template.yml", replacements))
    write_text(output_root / ".env.example", render_text(".env.example.template", replacements))
    write_text(
        output_root / "README.md",
        "\n".join(
            [
                f"# {args.display_name} OpenClaw Runtime",
                "",
                "Runtime gerado a partir do `setup-kit` do projeto `openclaw`.",
                "",
                "## Passos",
                "",
                "1. Copie `.env.example` para `.env` e preencha as chaves.",
                "2. Suba com `docker compose up -d`.",
                "3. Instale os cron jobs com `bash ./tools/install_whatsapp_ops.sh`.",
                "4. Faça o login do canal WhatsApp e revise os allowlists.",
                "",
            ],
        ),
    )

    for folder in ["workspace", "browsers", "config/diagnostics/whatsapp", "config/delivery-queue/processed"]:
        (output_root / folder).mkdir(parents=True, exist_ok=True)

    render_ops(output_root, args.container_name, args.account_id)

    print(json.dumps({"output": str(output_root), "clientSlug": args.client_slug}, ensure_ascii=False))


if __name__ == "__main__":
    main()
